# Use the official MySQL 8.0 image
FROM mysql:8.0

# Set MySQL root password and default database
ENV MYSQL_ROOT_PASSWORD=pw
ENV MYSQL_DATABASE=employees

# Copy initialization script to the correct directory
COPY ./mysql.sql /docker-entrypoint-initdb.d/

# Expose MySQL default port
EXPOSE 3306
